fix(samples): bug fix, added missing imports
googleapis/java-retail pull request #550
Opened 2022-09-22 09:24 UTC by dfirova

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-retail/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2022-09-23 22:14 UTC, chenlei1216 approved these changes

2022-09-27 14:31 UTC, kolea2 approved these changes

2022-09-28 22:05 UTC, kolea2 requested changes

2022-09-28 22:05 UTC, kolea2 commented on samples/interactive-tutorials/src/main/java/product/AddFulfillmentPlaces.java
> +//import com.google.protobuf.Timestamp;
why are these needed?

2022-09-29 08:08 UTC, dfirova commented
This PR is not relevant anymore. Closing it, all the changes will be made inside tutorials.

2022-09-29 08:08 UTC, closed without merging